import { LocalChainConfigType } from "./type";

export const stagingNetworks: LocalChainConfigType = {
  883: {
    name: "883",
    chainId: 883,
    rpcUrl: "http://localhost:8545",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  884: {
    name: "884",
    chainId: 884,
    rpcUrl: "http://localhost:8547",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  localhost: {
    name: "--",
    chainId: 31337,
    rpcUrl: "http://localhost:8545",
    iconUrl: "./defaultIcon.svg",
    symbol: "ETH",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  bscTest: {
    name: "BSC Testnet",
    chainId: 97,
    rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
    iconUrl: "./bsc.png",
    symbol: "BNB",
    blockExplorerUrl: "https://testnet.bscscan.com",
    tokenSymbolList: ["CELR", "USDT", "WETH", "DOMI", "MCB", "PSP", "PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["DOMI", "PSP", "MELI"],
  },
  ropsten: {
    name: "Ropsten Testnet",
    chainId: 3,
    rpcUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://ropsten.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  goerli: {
    name: "Goerli Testnet",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "TCELR", "USDC", "DOMI", "MCB", "cUSD", "PSP"],
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "PSP"],
  },
  mainnet: {
    name: "Ethereum Mainnet",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "oneDODO",
      "OLO",
      "BOBA",
      "XTK",
      "xXTKa",
      "PSP",
      "FRAX",
      "FXS",
      "CVP",
      "CEC",
      "Metis",
      "WXT",
      "PEOPLE",
      "STND",
      "SOS",
      "WBTC",
      "CELR",
      "WOO",
      "DF",
      "USX",
      "AMY",
      "DAI",
      "GHX",
      "KROM",
      "PERP",
      "TCR",
      "SAFLE",
      "PKEX",
      "CONV",
      "PERL",
      "TSD",
      "AAVE",
      "CRV",
      "SYS",
      "AVG",
      "AELIN",
      "JPEG",
      "CGG",
      "REVA",
      "MASK",
      "LUSD",
      "WAGMIV1",
      "REEF",
      "THALES",
      "DODO",
      "MELOS",
      "TORN",
      "MSU",
      "UCG",
      "HUH",
      "iZi",
      "ESW",
      "MGH",
      "ASTR",
      "BLANK",
      "ANML",
      "GOVI",
      "ONG",
      "DTR",
      "WAGMIV2",
      "RING",
      "DEVT",
      "GEL",
      "NFTY",
      "RLY",
      "AKRO",
      "SHI",
      "iUSD",
      "OOKI",
      "WAGMIV3",
      "EUX",
      "ONSTON",
      "UMA",
      "RAGE",
      "XBP",
      "FLX",
      "PLOT",
      "PBR",
      "cfUSDC",
      "SOLACE",
      "celrWFLOW",
      "LFI",
      "GNO",
      "WING",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "GOV",
      "PSTAKE",
      "SEAN",
      "JPYC",
      "DEO",
      "CERES",
      "FNCY",
      "S2K",
      "LEAP",
      "NYM",
    ],
    lqMintTokenSymbolBlackList: [
      "DOMI",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "FXS",
      "WXT",
      "PEOPLE",
      "SOS",
      "WBTC",
      "CELR",
      "AMY",
      "DAI",
      "GHX",
      "SAFLE",
      "PKEX",
      "CONV",
      "TSD",
      "AAVE",
      "CRV",
      "SYS",
      "AVG",
      "AELIN",
      "CGG",
      "REVA",
      "WAGMIV1",
      "MELOS",
      "MSU",
      "UCG",
      "MGH",
      "ASTR",
      "BLANK",
      "DTR",
      "WAGMIV2",
      "DEVT",
      "GEL",
      "NFTY",
      "RLY",
      "AKRO",
      "WAGMIV3",
      "UMA",
      "RAGE",
      "XBP",
      "FLX",
      "PLOT",
      "PBR",
      "SOLACE",
      "LFI",
      "GNO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "GOV",
      "PSTAKE",
      "SEAN",
      "DEO",
      "CERES",
      "FNCY",
      "S2K",
      "LEAP",
      "NYM",
    ],
  },
  bsc: {
    name: "BNB Chain",
    chainId: 56,
    rpcUrl: "https://bscrpc.com",
    iconUrl: "./bnbchain.png",
    symbol: "BNB",
    blockExplorerUrl: "https://bscscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "DOMI",
      "MCB",
      "cUSD",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "FXS",
      "CVP",
      "CEC",
      "ATL",
      "PEOPLE",
      "SOS",
      "BNB",
      "WOO",
      "DF",
      "USX",
      "GHX",
      "PERP",
      "SAFLE",
      "PERL",
      "WBNB",
      "TSD",
      "SYS",
      "AVG",
      "JPEG",
      "REVA",
      "MASK",
      "LUSD",
      "REEF",
      "SWAY",
      "JADE",
      "MELOS",
      "TORN",
      "MSU",
      "UCG",
      "HUH",
      "MGH",
      "ASVA",
      "ANML",
      "iZi",
      "ONG",
      "DTR",
      "AKRO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "SHI",
      "iUSD",
      "OOKI",
      "EUX",
      "PBR",
      "PEEL",
      "SHELL",
      "WRT",
      "GNO",
      "IDIA",
      "WING",
      "OKSE",
      "GOV",
      "PSTAKE",
      "FNCY",
      "S2K",
      "LEAP",
      "NYM",
    ],
    lqMintTokenSymbolBlackList: [
      "cUSD",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "FXS",
      "ATL",
      "PEOPLE",
      "SOS",
      "BNB",
      "GHX",
      "SAFLE",
      "WBNB",
      "TSD",
      "SYS",
      "AVG",
      "REVA",
      "LUSD",
      "SWAY",
      "JADE",
      "MELOS",
      "MSU",
      "UCG",
      "MGH",
      "DTR",
      "AKRO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "OOKI",
      "PBR",
      "PEEL",
      "SHELL",
      "WRT",
      "GNO",
      "IDIA",
      "OKSE",
      "GOV",
      "PSTAKE",
      "FNCY",
      "S2K",
      "LEAP",
      "NYM",
    ],
  },

  polygon: {
    name: "Polygon (Matic)",
    chainId: 137,
    rpcUrl: "https://rpc.ankr.com/polygon",
    iconUrl: "./polygon.png",
    symbol: "MATIC",
    blockExplorerUrl: "https://polygonscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "FRAX",
      "FXS",
      "WXT",
      "ATL",
      "MAI",
      "WOO",
      "SAFLE",
      "MATIC",
      "KROM",
      "REVA",
      "JONES",
      "SWAY",
      "HUH",
      "ESW",
      "DF",
      "USX",
      "ASVA",
      "ANML",
      "GOVI",
      "RING",
      "DEVT",
      "THALES",
      "iUSD",
      "EUX",
      "ONSTON",
      "OOKI",
      "iZi",
      "JPYC",
      "GEL",
      "AX",
      "MAI",
      "QI",
      "GREEN",
      "BIFI",
      "SOLACE",
      "OKSE",
      "LFI",
    ],
    lqMintTokenSymbolBlackList: [
      "FRAX",
      "FXS",
      "WXT",
      "ATL",
      "MAI",
      "SAFLE",
      "MATIC",
      "REVA",
      "JONES",
      "SWAY",
      "DEVT",
      "GEL",
      "AX",
      "MAI",
      "QI",
      "GREEN",
      "BIFI",
      "SOLACE",
      "OKSE",
      "LFI",
    ],
  },
  arbitrum: {
    name: "Arbitrum One",
    chainId: 42161,
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    iconUrl: "./arbitrum.png",
    symbol: "ETH",
    blockExplorerUrl: "https://arbiscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "DODO",
      "MCB",
      "XTK",
      "xXTKa",
      "FRAX",
      "FXS",
      "WOO",
      "DF",
      "USX",
      "AMY",
      "KROM",
      "PERP",
      "TCR",
      "REVA",
      "JONES",
      "iZi",
      "GOVI",
      "AKRO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "iUSD",
      "EUX",
      "OOKI",
      "OKSE",
    ],
    lqMintTokenSymbolBlackList: [
      "FRAX",
      "FXS",
      "AMY",
      "REVA",
      "JONES",
      "AKRO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "OKSE",
    ],
  },
  Avalanche: {
    name: "Avalanche",
    chainId: 43114,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    iconUrl: "./avalanche.png",
    symbol: "AVAX",
    blockExplorerUrl: "https://snowtrace.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "FRAX",
      "FXS",
      "WXT",
      "PEOPLE",
      "MAI",
      "SOS",
      "AVAX",
      "WOO",
      "ATL",
      "TSD",
      "DOMI",
      "CGG",
      "REVA",
      "LUSD",
      "JONES",
      "JPEG",
      "DODO",
      "JADE",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "JPYC",
      "CRA",
      "CRAM",
      "TUS",
      "ONSTON",
      "GNO",
      "USX",
      "OKSE",
      "avaxUSDC",
    ],
    lqMintTokenSymbolBlackList: [
      "FRAX",
      "FXS",
      "WXT",
      "PEOPLE",
      "MAI",
      "SOS",
      "AVAX",
      "ATL",
      "TSD",
      "CGG",
      "REVA",
      "LUSD",
      "JONES",
      "JADE",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "CRA",
      "CRAM",
      "TUS",
      "GNO",
      "OKSE",
      "avaxUSDC",
    ],
  },
  Optimism: {
    name: "Optimism",
    chainId: 10,
    rpcUrl: "https://opt-mainnet.g.alchemy.com/v2/PmGpTd85SWGf8488jy5H1--I09WBEkIl",
    walletRpcUrl: "https://mainnet.optimism.io",
    iconUrl: "./optimism.png",
    symbol: "ETH",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "LYRA",
      "DF",
      "USX",
      "KROM",
      "PERP",
      "FRAX",
      "FXS",
      "AELIN",
      "REVA",
      "THALES",
      "LUSD",
      "OKSE",
    ],
    lqMintTokenSymbolBlackList: ["FRAX", "FXS", "AELIN", "REVA", "OKSE"],
  },
  OptimisticKovan: {
    name: "Optimistic Kovan",
    chainId: 69,
    rpcUrl: "https://kovan.optimism.io",
    iconUrl: "./optimism.png",
    symbol: "ETH",
    blockExplorerUrl: "https://kovan-optimistic.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  Fantom: {
    name: "Fantom",
    chainId: 250,
    rpcUrl: "https://rpc.ankr.com/fantom",
    iconUrl: "./fantom.png",
    symbol: "FTM",
    blockExplorerUrl: "https://ftmscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "FRAX",
      "FXS",
      "PEOPLE",
      "SOS",
      "WOO",
      "FTM",
      "REVA",
      "LUSD",
      "BLANK",
      "GEL",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "SOLACE",
      "GNO",
      "OKSE",
    ],
    lqMintTokenSymbolBlackList: [
      "FRAX",
      "FXS",
      "PEOPLE",
      "SOS",
      "FTM",
      "REVA",
      "LUSD",
      "BLANK",
      "GEL",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "SOLACE",
      "GNO",
      "OKSE",
    ],
  },
  FantomTestnet: {
    name: "Fantom Testnet",
    chainId: 4002,
    rpcUrl: "https://rpc.testnet.fantom.network",
    iconUrl: "./fantom.png",
    symbol: "FTM",
    blockExplorerUrl: "https://testnet.ftmscan.com",
    tokenSymbolList: ["CELR", "USDT", "TCELR"],
    lqMintTokenSymbolBlackList: [],
  },

  Harmony: {
    name: "Harmony",
    chainId: 1666600000,
    rpcUrl: "https://api.harmony.one",
    iconUrl: "./harmony.png",
    symbol: "ONE",
    blockExplorerUrl: "https://explorer.harmony.one",
    tokenSymbolList: ["USDC", "WETH", "FRAX", "FXS", "PEOPLE", "MAI", "SOS", "REVA"],
    lqMintTokenSymbolBlackList: ["FRAX", "FXS", "PEOPLE", "MAI", "SOS", "REVA"],
  },

  Moonriver: {
    name: "Moonriver",
    chainId: 1285,
    rpcUrl: "https://rpc.moonriver.moonbeam.network",
    iconUrl: "./moonriver.png",
    symbol: "MOVR",
    blockExplorerUrl: "https://moonriver.moonscan.io",
    tokenSymbolList: ["SOS", "FRAX", "FXS", "PEOPLE", "USDC", "USDT", "WETH", "MAI", "DODO"],
    lqMintTokenSymbolBlackList: ["SOS", "FRAX", "FXS", "PEOPLE", "USDC", "USDT", "WETH", "MAI", "DODO"],
  },

  BoBa: {
    name: "Boba Network",
    chainId: 288,
    rpcUrl: "https://mainnet.boba.network",
    iconUrl: "./boba.png",
    symbol: "ETH",
    blockExplorerUrl: "https://blockexplorer.boba.network",
    tokenSymbolList: ["USDC", "OLO", "BOBA", "FRAX", "FXS", "WAGMIV1", "WAGMIV2", "WAGMIV3"],
    lqMintTokenSymbolBlackList: ["OLO", "FRAX", "FXS", "WAGMIV1", "WAGMIV2", "WAGMIV3"],
  },

  CeloTestnet: {
    name: "Celo Testnet",
    chainId: 44787,
    rpcUrl: "https://alfajores-forno.celo-testnet.org",
    iconUrl: "./celo.png",
    symbol: "CELO",
    blockExplorerUrl: "https://alfajores-blockscout.celo-testnet.org",
    tokenSymbolList: ["USDC", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "cUSD"],
  },

  Celo: {
    name: "Celo",
    chainId: 42220,
    rpcUrl: "https://forno.celo.org",
    iconUrl: "./celo.png",
    symbol: "CELO",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["USDC", "USDT", "cUSD", "WETH", "PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "cUSD", "WETH", "PEOPLE", "SOS"],
  },

  OKXChainTestnet: {
    name: "OKX Chain Testnet",
    chainId: 65,
    rpcUrl: "https://exchaintestrpc.okex.org",
    iconUrl: "./OKchain.png",
    symbol: "PCE",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["MELI"],
  },

  Aurora: {
    name: "Aurora",
    chainId: 1313161554,
    rpcUrl: "https://mainnet.aurora.dev",
    iconUrl: "./Aurora.png",
    symbol: "aETH",
    blockExplorerUrl: "https://explorer.mainnet.aurora.dev/",
    tokenSymbolList: ["USDC", "BNB", "AVAX", "FTM", "USDT", "FRAX", "FXS", "BUSD", "ESW", "AURORA", "SOLACE", "OKSE"],
    lqMintTokenSymbolBlackList: ["BNB", "AVAX", "FTM", "FRAX", "FXS", "BUSD", "AURORA", "SOLACE", "OKSE"],
  },

  Metis: {
    name: "Metis",
    chainId: 1088,
    rpcUrl: "https://andromeda.metis.io/?owner=1088",
    iconUrl: "./metis_chain.png",
    symbol: "Metis",
    blockExplorerUrl: "https://andromeda-explorer.metis.io/",
    tokenSymbolList: ["Metis", "STND", "PEOPLE", "WBTC", "CELR", "SOS", "ATL"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "WBTC", "CELR", "SOS", "ATL"],
  },

  OKXChain: {
    name: "OKX Chain",
    chainId: 66,
    rpcUrl: "https://exchainrpc.okex.org",
    iconUrl: "./oec.png",
    symbol: "OKT",
    blockExplorerUrl: "https://www.oklink.com/en/oec",
    tokenSymbolList: ["PEOPLE", "SOS", "MARK", "PLATO", "ONG", "WING", "OKSE"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS", "MARK", "PLATO", "OKSE"],
  },

  xDai: {
    name: "Gnosis Chain",
    chainId: 100,
    rpcUrl: "https://rpc.xdaichain.com",
    iconUrl: "./gnosis.png",
    symbol: "xDai",
    blockExplorerUrl: "https://blockscout.com/xdai/mainnet",
    tokenSymbolList: ["PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS"],
  },

  Heco: {
    name: "Heco",
    chainId: 128,
    rpcUrl: "https://http-mainnet.hecochain.com",
    iconUrl: "./heco.png",
    symbol: "HT",
    blockExplorerUrl: "https://hecoinfo.com",
    tokenSymbolList: ["PEOPLE", "SOS", "MARK", "PLATO", "RING"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS", "MARK", "PLATO"],
  },

  Oasis: {
    name: "Oasis Emerald",
    chainId: 42262,
    rpcUrl: "https://emerald.oasis.dev",
    iconUrl: "./oasis.png",
    symbol: "ROSE",
    blockExplorerUrl: "https://www.oasisscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "BNB", "AVAX", "FTM", "AMY", "DAI", "CELR"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH", "BNB", "AVAX", "FTM", "AMY", "DAI", "CELR"],
  },

  Moonbeam: {
    name: "Moonbeam",
    chainId: 1284,
    rpcUrl: "https://rpc.api.moonbeam.network",
    iconUrl: "./moonbeam.png",
    symbol: "GLMR",
    blockExplorerUrl: "https://moonbeam.moonscan.io",
    tokenSymbolList: ["USDC", "USDT", "CELR", "PEOPLE", "FRAX", "FXS", "CONV", "ZLK", "WETH", "WBTC", "BUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "CELR", "PEOPLE", "FRAX", "FXS", "CONV", "WETH", "WBTC", "BUSD"],
  },

  Astar: {
    name: "Astar",
    chainId: 592,
    rpcUrl: "https://rpc.astar.network:8545",
    iconUrl: "./astar.png",
    symbol: "ASTR",
    blockExplorerUrl: "https://blockscout.com/astar",
    tokenSymbolList: [
      "WETH",
      "USDT",
      "USDC",
      "DAI",
      "BNB",
      "BUSD",
      "PKEX",
      "WBTC",
      "SDN",
      "MATIC",
      "AAVE",
      "CRV",
      "ESW",
      "ASTR",
      "NFTY",
      "JPYC",
      "ZLK",
      "SEAN",
      "CERES",
      "DEO",
    ],
    lqMintTokenSymbolBlackList: [
      "WETH",
      "USDT",
      "DAI",
      "BNB",
      "BUSD",
      "WBTC",
      "SDN",
      "MATIC",
      "AAVE",
      "CRV",
      "ASTR",
      "NFTY",
      "SEAN",
      "CERES",
      "DEO",
    ],
  },
  Syscoin: {
    name: "Syscoin",
    chainId: 57,
    rpcUrl: "https://rpc.syscoin.org",
    iconUrl: "./syscoin.png",
    symbol: "SYS",
    blockExplorerUrl: "https://explorer.syscoin.org",
    tokenSymbolList: ["USDT", "USDC", "WETH", "WBTC", "BNB", "SYS", "DAI"],
    lqMintTokenSymbolBlackList: ["USDT", "USDC", "WETH", "WBTC", "BNB", "SYS", "DAI"],
  },
  Shiden: {
    name: "Shiden",
    chainId: 336,
    rpcUrl: "https://rpc.shiden.astar.network:8545",
    iconUrl: "./shiden.png",
    symbol: "SDN",
    blockExplorerUrl: "https://shiden.subscan.io",
    tokenSymbolList: ["SDN", "PKEX", "ESW"],
    lqMintTokenSymbolBlackList: ["SDN"],
  },
  Milkomeda: {
    name: "Milkomeda Cardano",
    chainId: 2001,
    rpcUrl: "https://rpc-mainnet-cardano-evm.c1.milkomeda.com",
    iconUrl: "./milkomeda.png",
    symbol: "ADA",
    blockExplorerUrl: "https://explorer-mainnet-cardano-evm.c1.milkomeda.com",
    tokenSymbolList: ["PKEX", "USDT", "USDC", "WETH", "WBTC", "DAI", "BNB", "BUSD", "AVAX", "FTM", "MATIC", "WRT"],
    lqMintTokenSymbolBlackList: ["USDT", "USDC", "WETH", "WBTC", "DAI", "BNB", "BUSD", "AVAX", "FTM", "MATIC", "WRT"],
  },

  MilkomedaA1Mainnet: {
    name: "Milkomeda A1 Mainnet",
    chainId: 2002,
    rpcUrl: "https://rpc-mainnet-algorand-rollup.a1.milkomeda.com",
    iconUrl: "./milkomeda.png",
    symbol: "mALGO",
    blockExplorerUrl: "https://explorer-mainnet-algorand-rollup.a1.milkomeda.com/",
    tokenSymbolList: ["USDT", "USDC", "WETH", "WBTC", "DAI", "BNB", "BUSD", "AVAX", "FTM", "MATIC"],
    lqMintTokenSymbolBlackList: ["USDT", "USDC", "WETH", "WBTC", "DAI", "BNB", "BUSD", "AVAX", "FTM", "MATIC"],
  },

  Evmos: {
    name: "Evmos",
    chainId: 9001,
    rpcUrl: "https://eth.bd.evmos.org:8545",
    iconUrl: "./evmos.png",
    symbol: "EVMOS",
    blockExplorerUrl: "https://evm.evmos.org/",
    tokenSymbolList: [
      "USDT",
      "USDC",
      "DAI",
      "WETH",
      "WBTC",
      "CELR",
      "BNB",
      "BUSD",
      "AVAX",
      "FTM",
      "AURORA",
      "FRAX",
      "FXS",
    ],
    lqMintTokenSymbolBlackList: [
      "USDT",
      "USDC",
      "DAI",
      "WETH",
      "WBTC",
      "CELR",
      "BNB",
      "BUSD",
      "AVAX",
      "FTM",
      "AURORA",
      "FRAX",
      "FXS",
    ],
  },

  CloverMainnet: {
    name: "Clover Mainnet",
    chainId: 1024,
    rpcUrl: "https://api-para.clover.finance",
    iconUrl: "./clover.png",
    symbol: "CLV",
    blockExplorerUrl: "https://clover.subscan.io",
    tokenSymbolList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
    lqMintTokenSymbolBlackList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
  },
  REI: {
    name: "REI Network",
    chainId: 47805,
    rpcUrl: "https://rpc.rei.network",
    iconUrl: "./REI.png",
    symbol: "REI",
    blockExplorerUrl: "https://scan.rei.network/",
    tokenSymbolList: ["WETH", "USDC", "USDT", "DAI", "WBTC", "BUSD"],
    lqMintTokenSymbolBlackList: ["WETH", "USDC", "USDT", "DAI", "WBTC", "BUSD"],
  },
  Conflux: {
    name: "Conflux",
    chainId: 1030,
    rpcUrl: "https://evm.confluxrpc.com",
    iconUrl: "./conflux.png",
    symbol: "CFX",
    blockExplorerUrl: "https://evm.confluxscan.net",
    tokenSymbolList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
    lqMintTokenSymbolBlackList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
  },

  Ontology: {
    name: "Ontology",
    chainId: 58,
    rpcUrl: "https://dappnode10.ont.io:10339",
    iconUrl: "./ontology.svg",
    symbol: "ONG",
    blockExplorerUrl: "https://explorer.ont.io",
    tokenSymbolList: ["ONG", "USDC", "USDT", "WETH", "WBTC", "WING"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH", "WBTC"],
  },

  flowMainnet: {
    name: "Flow",
    chainId: 12340001,
    rpcUrl: "",
    iconUrl: "./FLOW.png",
    symbol: "FlowToken",
    blockExplorerUrl: "https://flowscan.org/",
    tokenSymbolList: [
      "AVAX",
      "BNB",
      "BUSD",
      "DAI",
      "FTM",
      "MATIC",
      "USDT",
      "WBTC",
      "WETH",
      "RLY",
      "cfUSDC",
      "celrWFLOW",
    ],
    lqMintTokenSymbolBlackList: ["AVAX", "BNB", "BUSD", "DAI", "FTM", "MATIC", "USDT", "WBTC", "WETH", "RLY"],
  },

  CrabSmartChain: {
    name: "Crab Smart Chain",
    chainId: 44,
    rpcUrl: "https://crab-rpc.darwinia.network",
    iconUrl: "./crab.png",
    symbol: "CRAB",
    blockExplorerUrl: "https://subview.xyz",
    tokenSymbolList: ["RING", "USDC", "USDT"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT"],
  },
  PlatON: {
    name: "PlatON",
    chainId: 210425,
    rpcUrl: "https://openapi2.platon.network/rpc",
    iconUrl: "./platon.png",
    symbol: "LAT",
    blockExplorerUrl: "https://scan.platon.network/",
    tokenSymbolList: ["USDT", "USDC", "WETH", "DAI", "WBTC"],
    lqMintTokenSymbolBlackList: ["USDT", "USDC", "WETH", "DAI", "WBTC"],
  },
  Swimmer: {
    name: "Swimmer Network",
    chainId: 73772,
    rpcUrl: "https://rpc.swimmer.network/ext/bc/2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX/rpc",
    iconUrl: "./swimmer.png",
    symbol: "TUS",
    blockExplorerUrl: "https://explorer.swimmer.network/",
    tokenSymbolList: ["CRA", "CRAM", "TUS", "USDC", "avaxUSDC"],
    lqMintTokenSymbolBlackList: ["CRA", "CRAM", "TUS", "USDC", "avaxUSDC"],
  },
  SXNetwork: {
    name: "SX Network",
    chainId: 416,
    rpcUrl: "https://rpc.sx.technology",
    iconUrl: "./sx.png",
    symbol: "SX",
    blockExplorerUrl: "https://explorer.sx.technology",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "WBTC",
      "DAI",
      "MATIC",
      "UMA",
      "RAGE",
      "XBP",
      "FLX",
      "CELR",
      "PLOT",
      "AX",
      "MAI",
      "QI",
      "GREEN",
      "BIFI",
      "LFI",
    ],
    lqMintTokenSymbolBlackList: [
      "USDC",
      "USDT",
      "WETH",
      "WBTC",
      "DAI",
      "MATIC",
      "UMA",
      "RAGE",
      "XBP",
      "FLX",
      "CELR",
      "PLOT",
      "AX",
      "MAI",
      "QI",
      "GREEN",
      "BIFI",
      "LFI",
    ],
  },

  ApeChain: {
    name: "Ape Chain",
    chainId: 16350,
    rpcUrl: "https://bas.metaapesgame.com/bas_mainnet_full_rpc",
    iconUrl: "./ape.png",
    symbol: "PEEL",
    blockExplorerUrl: "https://explorer.bas.metaapesgame.com",
    tokenSymbolList: ["PEEL", "SHELL"],
    lqMintTokenSymbolBlackList: ["PEEL", "SHELL"],
  },
  KavaEVMCoChain: {
    name: "Kava EVM Co-Chain",
    chainId: 2222,
    rpcUrl: "https://evm.kava.io",
    iconUrl: "./kava.png",
    symbol: "KAVA",
    blockExplorerUrl: "https://explorer.kava.io",
    tokenSymbolList: ["USDC", "USDT", "DAI", "WETH", "WBTC", "IDIA", "USX"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "DAI", "WETH", "WBTC", "IDIA"],
  },
  NervosGodwoken: {
    name: "Nervos Godwoken",
    chainId: 71402,
    rpcUrl: "https://v1.mainnet.godwoken.io/rpc",
    iconUrl: "./nervos.png",
    symbol: "pCKB",
    blockExplorerUrl: "https://gw-mainnet-explorer.nervosdao.community",
    tokenSymbolList: ["USDC", "USDT", "DAI", "WETH", "WBTC", "BUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "DAI", "WETH", "WBTC", "BUSD"],
  },
  Klaytn: {
    name: "Klaytn",
    chainId: 8217,
    rpcUrl: "https://public-node-api.klaytnapi.com/v1/cypress",
    iconUrl: "./klaytn.png",
    symbol: "KLAY",
    blockExplorerUrl: "https://www.klaytnfinder.io",
    tokenSymbolList: ["USDC", "USDT", "DAI", "WETH", "WBTC"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "DAI", "WETH", "WBTC"],
  },
  ArbitrumNova: {
    name: "Arbitrum Nova",
    chainId: 42170,
    rpcUrl: "https://nova.arbitrum.io/rpc",
    iconUrl: "./arbitrumnova.png",
    symbol: "ETH",
    blockExplorerUrl: "https://nova-explorer.arbitrum.io",
    tokenSymbolList: ["USDC", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  FNCYChain: {
    name: "FNCY Chain",
    chainId: 73,
    rpcUrl: "https://fncy-seed1.fncy.world",
    iconUrl: "./FNCYChain.png",
    symbol: "FNCY",
    blockExplorerUrl: "https://fncyscan.fncy.world",
    tokenSymbolList: ["FNCY", "BUSD"],
    lqMintTokenSymbolBlackList: ["FNCY", "BUSD"],
  },
  AptosMainnet: {
    name: "Aptos Mainnet",
    chainId: 12360001,
    rpcUrl: "https://fullnode.mainnet.aptoslabs.com",
    iconUrl: "./aptos.png",
    symbol: "APTOS",
    blockExplorerUrl: "https://explorer.aptoslabs.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "WBTC", "DAI", "BUSD", "BNB"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH", "WBTC", "DAI", "BUSD", "BNB"],
  },
};
