import { LocalChainConfigType } from "./type";

export const basTestNetworks: LocalChainConfigType = {
  bscTest: {
    name: "BSC Testnet",
    chainId: 97,
    rpcUrl: "https://bsc-testnet.nodereal.io/v1/bdc0906a6f534a4598cdb24425cc855a",
    iconUrl: "./bnbchain.png",
    symbol: "BNB",
    blockExplorerUrl: "https://testnet.bscscan.com",
    tokenSymbolList: ["BNB", "BAS", "BUSD", "ARS", "BAS-MA", "SHELL", "GAL", "RNS", "CUBE"],
    lqMintTokenSymbolBlackList: ["SHELL", "GAL", "RNS", "CUBE"],
  },
  goerli: {
    name: "Goerli Testnet",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "TCELR", "USDC", "DOMI", "MCB", "cUSD", "PSP", "LUNA", "testtoken", "APTTEST"],
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "PSP", "LUNA", "testtoken", "APTTEST"],
  },
  BASTestnet: {
    name: "BAS Testnet",
    chainId: 14000,
    rpcUrl: "https://rpc.dev-01.bas.ankr.com/",
    iconUrl: "./bas.png",
    symbol: "BAS",
    blockExplorerUrl: "https://explorer.dev-01.bas.ankr.com/",
    tokenSymbolList: ["BAS", "BNB", "BUSD", "ARS"],
    lqMintTokenSymbolBlackList: [],
  },
  BASAries: {
    name: "BAS Aries Testnet",
    chainId: 117,
    rpcUrl: "https://bas-aries-public.nodereal.io/",
    iconUrl: "./bsc_aries.png",
    symbol: "ARS",
    blockExplorerUrl: "https://bas-aries-testnet-explorer.nodereal.io/",
    tokenSymbolList: ["BNB", "BUSD", "ARS", "BAS"],
    lqMintTokenSymbolBlackList: [],
  },
  BASMA: {
    name: "Meta Apes BAS Testnet",
    chainId: 15001,
    rpcUrl: "https://meta-ape-bas-testnet-01.ankr.com",
    iconUrl: "./bas_apes.png",
    symbol: "BAS-MA",
    blockExplorerUrl: "https://explorer.meta-ape-bas-testnet-02.ankr.com",
    tokenSymbolList: ["BNB", "BAS-MA", "SHELL"],
    lqMintTokenSymbolBlackList: [],
  },

  BASGalaxy: {
    name: "BAS Galaxy Testnet",
    chainId: 230,
    rpcUrl: "https://bas-galaxy-testnet.nodereal.io",
    iconUrl: "./bas_galaxy.png",
    symbol: "GAL",
    blockExplorerUrl: "https://bas-galaxy-testnet-explorer.nodereal.io",
    tokenSymbolList: ["BNB", "BUSD", "GAL"],
    lqMintTokenSymbolBlackList: ["BNB", "BUSD", "GAL"],
  },
  BASRNS: {
    name: "BAS RNS Testnet",
    chainId: 231,
    rpcUrl: "https://bas-rns-testnet.nodereal.io",
    iconUrl: "./bas_rns.png",
    symbol: "RNS",
    blockExplorerUrl: "https://bas-rns-testnet-explorer.nodereal.io",
    tokenSymbolList: ["BNB", "BUSD", "RNS"],
    lqMintTokenSymbolBlackList: ["BNB", "BUSD", "RNS"],
  },
  BASCUBE: {
    name: "BAS CUBE Testnet",
    chainId: 232,
    rpcUrl: "https://bas-cube-testnet.nodereal.io",
    iconUrl: "./bas_cube.png",
    symbol: "CUBE",
    blockExplorerUrl: "https://bas-cube-testnet-explorer.nodereal.io",
    tokenSymbolList: ["BNB", "BUSD", "CUBE"],
    lqMintTokenSymbolBlackList: ["BNB", "BUSD", "CUBE"],
  },
  AptosDevnet: {
    name: "Aptos Devnet",
    chainId: 12360003,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "./aptos.png",
    symbol: "APTTTT",
    blockExplorerUrl: "https://explorer.devnet.aptos.dev",
    tokenSymbolList: ["APTTEST"],
    lqMintTokenSymbolBlackList: ["APTTEST"],
  }
};
