import { LocalChainConfigType } from "./type";

export const testNetworks: LocalChainConfigType = {
  883: {
    name: "883",
    chainId: 883,
    rpcUrl: "http://localhost:8545",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  884: {
    name: "884",
    chainId: 884,
    rpcUrl: "http://localhost:8547",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  localhost: {
    name: "--",
    chainId: 31337,
    rpcUrl: "http://localhost:8545",
    iconUrl: "./defaultIcon.svg",
    symbol: "ETH",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  bscTest: {
    name: "BSC Testnet",
    chainId: 97,
    rpcUrl: "https://bsc-testnet.nodereal.io/v1/60abea8408e44c1282428c2343b4e1d8",
    // rpcUrl: "https://bsctestapi.terminet.io/rpc",
    iconUrl: "./bsc.png",
    symbol: "BNB",
    blockExplorerUrl: "https://testnet.bscscan.com",
    tokenSymbolList: [
      "CELR",
      "USDT",
      "WETH",
      "MCB",
      "PSP",
      "PCE",
      "MELI",
      "FUSD",
      "FLOW",
      "pmtUSDT",
      "USDC",
      "pegUSDT",
      "DAI",
      "CUBE",
      "BUSD",
      "FNCY",
    ],
    lqMintTokenSymbolBlackList: ["PSP", "MELI", "FUSD", "FLOW", "pmtUSDT", "pegUSDT", "CUBE", "BUSD", "FNCY"],
  },
  ropsten: {
    name: "Ropsten Testnet",
    chainId: 3,
    rpcUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://ropsten.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "FUSD", "FLOW", "USDC"],
    lqMintTokenSymbolBlackList: ["FUSD", "FLOW", "USDC"],
  },
  goerli: {
    name: "Goerli Testnet",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: [
      "CELR",
      "USDT",
      "WETH",
      "TCELR",
      "USDC",
      "DOMI",
      "MCB",
      "cUSD",
      "PSP",
      "LUNA",
      "TESTTOKEN",
      "pmtUSDT",
      "pegUSDT",
      "DAI",
      "FNCY",
      "APTOS",
      "usei",
      "uceler",
      "WBTC",
      "INJ",
    ],
    lqMintTokenSymbolBlackList: [
      "DOMI",
      "cUSD",
      "PSP",
      "LUNA",
      "TESTTOKEN",
      "pmtUSDT",
      "pegUSDT",
      "FNCY",
      "APTOS",
      "usei",
      "uceler",
      "WBTC",
      "INJ",
    ],
  },
  mainnet: {
    name: "Ethereum Mainnet",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "FRAX",
      "ONG",
    ],
    lqMintTokenSymbolBlackList: ["DOMI", "oneDODO", "OLO", "FRAX"],
  },

  polygon: {
    name: "Polygon (Matic)",
    chainId: 137,
    rpcUrl: "https://rpc.ankr.com/polygon",
    iconUrl: "./polygon.png",
    symbol: "MATIC",
    blockExplorerUrl: "https://polygonscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX", "SWAY"],
    lqMintTokenSymbolBlackList: ["SWAY"],
  },
  arbitrum: {
    name: "Arbitrum",
    chainId: 42161,
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    iconUrl: "./arbitrum.png",
    symbol: "ETH",
    blockExplorerUrl: "https://arbiscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "DODO", "MCB", "IMX"],
    lqMintTokenSymbolBlackList: [],
  },
  Avalanche: {
    name: "Avalanche",
    chainId: 43114,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    iconUrl: "./avalanche.png",
    symbol: "AVAX",
    blockExplorerUrl: "https://snowtrace.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX"],
    lqMintTokenSymbolBlackList: [],
  },
  Optimism: {
    name: "Optimism",
    chainId: 10,
    rpcUrl: "https://mainnet.optimism.io",
    iconUrl: "./optimism.png",
    symbol: "ETH",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "LYRA"],
    lqMintTokenSymbolBlackList: [],
  },
  OptimisticKovan: {
    name: "Optimistic Kovan",
    chainId: 69,
    rpcUrl: "https://kovan.optimism.io",
    iconUrl: "./optimism.png",
    symbol: "ETH",
    blockExplorerUrl: "https://kovan-optimistic.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  Fantom: {
    name: "Fantom",
    chainId: 250,
    rpcUrl: "https://rpc.ankr.com/fantom",
    iconUrl: "./fantom.png",
    symbol: "FTM",
    blockExplorerUrl: "https://ftmscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  FantomTestnet: {
    name: "Fantom Testnet",
    chainId: 4002,
    rpcUrl: "https://rpc.testnet.fantom.network",
    iconUrl: "./fantom.png",
    symbol: "FTM",
    blockExplorerUrl: "https://testnet.ftmscan.com",
    tokenSymbolList: ["CELR", "USDT", "TCELR", "WETH", "PSP", "MCB"],
    lqMintTokenSymbolBlackList: ["WETH", "PSP"],
  },

  // Harmony: {
  //   name: "Harmony",
  //   color: "#3099f2",
  //   chainId: 1666600000,
  //   rpcUrl: "https://api.harmony.one",
  //   blockTime: 5000,
  //   iconUrl: "./harmony.png",
  //   blockDelay: 20,
  //   symbol: "ONE",
  //   blockExplorerUrl: "https://explorer.harmony.one",
  //   tokenSymbolList: ["USDC", "WETH"],
  // lqMintTokenSymbolBlackList:[]
  // },

  // Moonriver: {
  //   name: "Moonriver",
  //   color: "#3099f2",
  //   chainId: 1285,
  //   rpcUrl: "https://rpc.moonriver.moonbeam.network",
  //   blockTime: 5000,
  //   iconUrl: "./moonriver.png",
  //   blockDelay: 20,
  //   symbol: "MOVR",
  //   blockExplorerUrl: "https://moonriver.moonscan.io",
  //   tokenSymbolList: ["USDC"],
  // lqMintTokenSymbolBlackList:[]
  // },

  BoBa: {
    name: "Boba Network",
    chainId: 288,
    rpcUrl: "https://mainnet.boba.network",
    iconUrl: "./boba.png",
    symbol: "ETH",
    blockExplorerUrl: "https://blockexplorer.boba.network",
    tokenSymbolList: ["USDC", "OLO", "BOBA"],
    lqMintTokenSymbolBlackList: ["OLO"],
  },

  CeloTestnet: {
    name: "Celo Testnet",
    chainId: 44787,
    rpcUrl: "https://alfajores-forno.celo-testnet.org",
    iconUrl: "./celo.png",
    symbol: "CELO",
    blockExplorerUrl: "https://alfajores-blockscout.celo-testnet.org",
    tokenSymbolList: ["USDC", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "cUSD"],
  },

  Celo: {
    name: "Celo",
    chainId: 42220,
    rpcUrl: "https://forno.celo.org",
    iconUrl: "./celo.png",
    symbol: "CELO",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["USDC", "USDT", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "cUSD"],
  },

  OKXChainTestnet: {
    name: "OKX Chain Testnet",
    chainId: 65,
    rpcUrl: "https://exchaintestrpc.okex.org",
    iconUrl: "./OKchain.png",
    symbol: "PCE",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["PCE", "MELI", "ONG"],
    lqMintTokenSymbolBlackList: ["MELI"],
  },
  MoonbaseAlpha: {
    name: "Moonbase Alpha",
    chainId: 1287,
    rpcUrl: "https://rpc.api.moonbase.moonbeam.network",
    iconUrl: "./moonriver.png",
    symbol: "DEV",
    blockExplorerUrl: "https://moonbase-blockscout.testnet.moonbeam.network/",
    tokenSymbolList: ["USDC", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH"],
  },

  REITestnet: {
    name: "REI Testnet",
    chainId: 12357,
    rpcUrl: "https://rpc-testnet.rei.network",
    iconUrl: "./GXChain.png",
    symbol: "DEV",
    blockExplorerUrl: "https://scan-test.rei.network",
    tokenSymbolList: ["USDC"],
    lqMintTokenSymbolBlackList: ["USDC"],
  },

  OasisTestnet: {
    name: "Emerald Paratime Testnet",
    chainId: 42261,
    rpcUrl: "https://testnet.emerald.oasis.dev",
    iconUrl: "./oasis.png",
    symbol: "ROSE",
    blockExplorerUrl: "https://explorer.testnet.oasis.updev.si",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: ["USDT"],
  },
  CloverTestnet: {
    name: "Clover Testnet",
    chainId: 1023,
    rpcUrl: "https://rpc.clover.finance",
    iconUrl: "./clover.png",
    symbol: "CLV",
    blockExplorerUrl: "",
    tokenSymbolList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
    lqMintTokenSymbolBlackList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
  },
  CloverMainnet: {
    name: "Clover Mainnet",
    chainId: 1024,
    rpcUrl: "https://api-para.clover.finance",
    iconUrl: "./clover.png",
    symbol: "CLV",
    blockExplorerUrl: "https://clover.subscan.io",
    tokenSymbolList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
    lqMintTokenSymbolBlackList: ["WETH", "USDC", "USDT", "DAI", "WBTC"],
  },

  flowTest: {
    name: "Flow Testnet",
    chainId: 12340002,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./FLOW.png",
    symbol: "FlowToken",
    blockExplorerUrl: "https://testnet.flowscan.org/",
    tokenSymbolList: ["FUSD", "FLOW", "USDC", "FLOWUSDC", "TESTTOKEN"],
    lqMintTokenSymbolBlackList: ["FUSD", "FLOW", "USDC", "TESTTOKEN"],
  },

  terraTest: {
    name: "Terra Bombay-12",
    chainId: 999999999,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./Terra.png",
    symbol: "LUNA",
    blockExplorerUrl: "https://finder.terra.money/testnet",
    tokenSymbolList: ["LUNA"],
    lqMintTokenSymbolBlackList: ["LUNA"],
  },
  Ontology: {
    name: "Ontology Testnet",
    chainId: 5851,
    rpcUrl: "https://dappnode1.ont.io:20339",
    iconUrl: "./ontology.svg",
    symbol: "ONG",
    blockExplorerUrl: "https://explorer.ont.io",
    tokenSymbolList: ["ONG"],
    lqMintTokenSymbolBlackList: [],
  },
  SXTest: {
    name: "Toronto SX",
    chainId: 647,
    rpcUrl: "https://rpc.toronto.sx.technology",
    iconUrl: "./sx.png",
    symbol: "SX",
    blockExplorerUrl: "https://explorer.toronto.sx.technology",
    tokenSymbolList: ["WETH", "USDC", "MATIC", "MCB"],
    lqMintTokenSymbolBlackList: ["WETH", "MATIC"],
  },
  PolygonTest: {
    name: "Polygon Mumbai",
    chainId: 80001,
    rpcUrl: "https://rpc-mumbai.matic.today",
    iconUrl: "./polygon.png",
    symbol: "MATIC",
    blockExplorerUrl: "https://mumbai.polygonscan.com",
    tokenSymbolList: ["MATIC", "USDC", "FLOWUSDC"],
    lqMintTokenSymbolBlackList: ["MATIC"],
  },

  AvalancheFujiTestnet: {
    name: "Avalanche Fuji Testnet",
    chainId: 43113,
    rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
    iconUrl: "./avalanche.png",
    symbol: "AVAX",
    blockExplorerUrl: "https://testnet.snowtrace.io",
    tokenSymbolList: ["CRA", "CRAM", "TUS"],
    lqMintTokenSymbolBlackList: ["CRA", "CRAM", "TUS"],
  },
  SwimmerTest: {
    name: "Swimmer Testnet",
    chainId: 73771,
    rpcUrl: "https://testnet-rpc.swimmer.network/ext/bc/2hUULz82ZYMKwjBHZybVRyouk38EmcW7UKP4iocf9rghpvfm84/rpc",
    iconUrl: "./swimmer.png",
    symbol: "TUS",
    blockExplorerUrl: "https://testnet-explorer.swimmer.network",
    tokenSymbolList: ["CRA", "CRAM", "TUS"],
    lqMintTokenSymbolBlackList: ["CRA", "CRAM", "TUS"],
  },
  NervosGodwokenTestnet: {
    name: "Nervos Godwoken Testnet",
    chainId: 71401,
    rpcUrl: "https://godwoken-testnet-v1.ckbapp.dev",
    iconUrl: "./nervos.png",
    symbol: "CKB",
    blockExplorerUrl: "https://gw-explorer.nervosdao.community",
    tokenSymbolList: ["USDC", "USDT"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT"],
  },
  FNCYTestnet: {
    name: "FNCY Testnet",
    chainId: 923018,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "./cube.png",
    symbol: "FNCY",
    blockExplorerUrl: "https://bas-cube-devnet-explorer.nodereal.io",
    tokenSymbolList: ["FNCY", "BUSD"],
    lqMintTokenSymbolBlackList: ["FNCY", "BUSD"],
  },
  AptosDevnet: {
    name: "Aptos Devnet",
    chainId: 12360003,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "https://get.celer.app/cbridge-icons/ETH.png",
    symbol: "APTTTT",
    blockExplorerUrl: "https://explorer.devnet.aptos.dev",
    tokenSymbolList: ["APTTEST"],
    lqMintTokenSymbolBlackList: ["APTTEST"],
  },
  AptosTestnet: {
    name: "Aptos Testnet",
    chainId: 12360002,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "./aptos.png",
    symbol: "APTTTT",
    blockExplorerUrl: "https://explorer.aptoslabs.com",
    tokenSymbolList: ["USDC", "APTOS", "WETH"],
    lqMintTokenSymbolBlackList: ["USDC", "APTOS", "WETH"],
  },
  ZKSyncTestnet: {
    name: "zksync testnet",
    chainId: 280,
    rpcUrl: "https://zksync2-testnet.zksync.dev",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://zksync2-testnet.zkscan.io",
    tokenSymbolList: ["USDC"],
    lqMintTokenSymbolBlackList: [],
  },
  OasysHubTestnet: {
    name: "Oasys Hub Testnet",
    chainId: 9372,
    rpcUrl: "https://rpc.testnet.oasys.games",
    iconUrl: "./oasysHub.png",
    symbol: "OAS",
    blockExplorerUrl: "https://explorer.testnet.oasys.games",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: ["USDT"],
  },
  seiTestnet: {
    name: "Sei Testnet",
    chainId: 999999998,
    rpcUrl: "https://sei-chain-incentivized.com/sei-chain-tm/",
    iconUrl: "./sei.png",
    symbol: "usei",
    blockExplorerUrl: "https://sei.explorers.guru/",
    tokenSymbolList: ["USDC", "USDT", "usei", "uceler", "WBTC"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "usei", "uceler", "WBTC"],
  },
  injectiveTestnet: {
    name: "Injective Testnet",
    chainId: 999999997,
    rpcUrl: "https://im-staging-api.celer.network/injective/",
    iconUrl: "./sei.png",
    symbol: "INJ",
    blockExplorerUrl: "https://testnet.explorer.injective.network/",
    tokenSymbolList: ["INJ", "USDT", "USDC"],
    lqMintTokenSymbolBlackList: ["INJ", "USDT", "USDC"],
  },
};
