import { LocalChainConfigType } from "./type";

export const aptosNetwork: LocalChainConfigType = {
  883: {
    name: "883",
    chainId: 883,
    rpcUrl: "http://localhost:8545",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  884: {
    name: "884",
    chainId: 884,
    rpcUrl: "http://localhost:8547",
    iconUrl: "./noChain.png",
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  ropsten: {
    name: "Ropsten Testnet",
    chainId: 3,
    rpcUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://ropsten.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "FUSD", "FLOW", "USDC"],
    lqMintTokenSymbolBlackList: ["FUSD", "FLOW", "USDC"],
  },
  goerli: {
    name: "Goerli Testnet",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: ["USDC", "USDT", "DAI", "WBTC", "WETH", "APTOS"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "DAI", "WBTC", "WETH", "APTOS"],
  },
  mainnet: {
    name: "Ethereum Mainnet",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    iconUrl: "./ETH.png",
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "FRAX",
      "ONG",
    ],
    lqMintTokenSymbolBlackList: ["DOMI", "oneDODO", "OLO", "FRAX"],
  },
  AptosDevnet: {
    name: "Aptos Devnet",
    chainId: 12360003,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "./aptos.png",
    symbol: "APTTTT",
    blockExplorerUrl: "https://explorer.aptoslabs.com",
    tokenSymbolList: ["USDC", "USDT", "DAI", "WBTC", "WETH"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "DAI", "WBTC", "WETH"],
  },
  AptosTestnet: {
    name: "Aptos Testnet",
    chainId: 12360002,
    rpcUrl: "https://bas-cube-devnet.nodereal.io",
    iconUrl: "./aptos.png",
    symbol: "APTTTT",
    blockExplorerUrl: "https://explorer.aptoslabs.com",
    tokenSymbolList: ["USDC", "APTOS", "WETH"],
    lqMintTokenSymbolBlackList: ["USDC", "APTOS", "WETH"],
  }
};
