stepImgName="seo_Arbitrum_Polygon"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. "


Chain_Full_1="Ethereum Mainnet"
Chain_Common_1="Ethereum"
Chain_cBridge_1="Ethereum Mainnet"
Chain_Info1=""
Chain_Info1_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info1_TokenFull="Ether"
Chain_Info1_TokenTicker="ETH"
Chain_Info1_BridgedTokenTicker="WETH"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2="Ethereum"
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info1_Token_AssetFullName="Ether"
Chain_Info1_Token_TradingSymbol="ETH"
Chain_Info1_Token_PriceUSD="1,221.61"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info1_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. "


Chain_Full_2="BNB Chain"
Chain_Common_2="BNB"
Chain_cBridge_2="BNB Chain"
Chain_Common_the_2="a"
Chain_Info2=""
Chain_Info2_Description="The BNB Chain, often referred to as Binance Smart Chain (BSC) or the Binance Chain, is composed of both the BSC and Binance Chain combined. The BNB Chain (abbreviation for “Build, ‘N Build”) enables BNB Chain governance for things like staking and voting.It also remains Ethereum Virtual Machine (EVM) compatible. The BNB Chain aims to increase interoperability across the blockchain ecosystem and develop the core infrastructure to enable and connect the “world’s parallel virtual environment.” With more new and improved features than its two separate parts, the BNB Chain has a boosted BSC throughout, is able to introduce an on-chain governance mechanism, have one-to-many chain scaling, and has overall improved scaling solutions. Plus  it has expanded the number of BSC validator sets from 21 to 41!<br><br>The six key pillars of the BNB Chain include being permissionless, decentralized, open, multichain accessible, designed for creators and inventors, and with the goal to be bigger than Binance itself."
Chain_Info2_TokenFull="BNB"
Chain_Info2_TokenTicker="BNB"
Chain_Info2_BridgedTokenTicker="muxBNB"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/BNB.png"
Chain_Info2_Token_AssetFullName="BNB"
Chain_Info2_Token_TradingSymbol="BNB"
Chain_Info2_Token_PriceUSD="0.00"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/bnb/"
Chain_Info2_Token_Description1="BNB is the native cryptocurrency token that fuels the <a href='https://www.bnbchain.org/en' class='a-config' target='_blank'>BNB Chain</a> ecosystem and serves as a governance and utility token fueling transactions on the BNB Chain, similar to gas on Ethereum. <br><br>Whether you want to simply transfer some BNB between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone has built on BNB; anytime you interact with BNB Chain you will be required to pay a small fee in BNB. BNB can be traded like other cryptocurrencies and widely used in various apps and use cases, including reducing Binance exchange trading fees, paying for transaction fees made via the BNB Chain, and purchasing goods and services online and in-store. <br><br>With many large-scale applications in Metaverse, GameFi, SocialFi and others being incorporated into the BNB Chain, Binance is positioning BNB as a token for the Binance ecosystem, which serves several sectors."

# <a href='https://fantom.foundation/' class='a-config' target='_blank'>Fantom</a>