stepImgName="seo_Avalanche_Ethereum_USDC"
indexType="one_wallet"

TokenFull="USD Coin"
TokenTicker="USDC"
BridgedTokenTicker="fUSDC"
TokenAKA_1=""
TokenAKA_2=""
Token_Icon="https://get.celer.app/cbridge-icons/USDC.png"
TokenInfo=""
TokenInfo_AssetFullName="USD Coin"
TokenInfo_TradingSymbol="USDC"
TokenInfo_PriceSymbol="USDC"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/USDC.png"
TokenInfo_PriceUSD="0.00"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/usd-coin/"
TokenInfo_Description1="USD Coin or more commonly referred to as <a href='https://www.circle.com/en/usdc' class='a-config' target='_blank'>USDC</a> is a digital dollar where \$1 of USDC is equal to \$1 USD. USDC is one the most popular stablecoins because of the level of transparency of the collateralized assets. As collateral, every USDC is backed by cash and short-term U.S. government bonds, so for every 1 USDC in circulation it is backed by \$1 USD. Hence, many refer to USDC as a fiat-collateralized stablecoin.<br><br>As a digital dollar, USDC is available 24/7 and is native to the internet. Some common use cases for USDC is to purchase it for a medium of exchange, using it on exchanges, storing in crypto wallets, fund purchases and trade for other cryptocurrencies.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of USDC <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/USDC.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is USD Coin and the ticker of this asset is USDC."



Chain_Full_1="Avalanche Network"
Chain_Common_1="Avalanche"
Chain_cBridge_1="Avalanche"
Chain_Info1=""
Chain_Info1_ChainId=43114
Chain_Info1_Description="Avalanche, as a layer one blockchain, is an open programmable smart contracts platform for decentralized applications. Similar to other layer one blockchains, Avalanche supports a wide spectrum of applications related to DeFi, gaming, NFTs, the metaverse, as well as support for stablecoins. Avalanche is composed of three key components that make up the blockchain: (1). The Platform Chain (P-Chain) which coordinates validators and the creation of subnets, (2). the C-Chain for the creation of smart contracts, and (3). the X-Chain for managing and exchanging assets.<br><br>As an Ethereum Virtual Machine (EVM) compatible platform, applications that are built using the Ethereum programming language Solidity are also able to be deployed on Avalanche with minimal modifications. This enables developers from one of the largest and widely adopted blockchain communities to build on Avalanche and to deploy custom private or public blockchains as “subnets.”"
Chain_Info1_TokenFull="Avalanche"
Chain_Info1_TokenTicker="AVAX"
Chain_Info1_BridgedTokenTicker="muxAVAX"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/AVAX.png"
Chain_Info1_Token_AssetFullName="Avalanche"
Chain_Info1_Token_TradingSymbol="AVAX"
Chain_Info1_Token_PriceSymbol="AVAX"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/avalanche/"
Chain_Info1_Token_Description1="AVAX is the native cryptocurrency of <a href='https://www.avax.network/' class='a-config' target='_blank'>Avalanche</a> with 720 million AVAX coins in circulation.  AVAX is used to help drive development across the network and can be used for staking and paying for transaction fees. It can also be used in proposing and voting on future network upgrades. In other words, AVAX is the currency of Avalanche and the applications running on it. Whether you want to simply transfer some AVAX between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Avalanche; anytime you interact with Avalanche you will be required to pay a small fee in AVAX.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of AVAX <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/AVAX.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Avalanche and the ticker of this asset is AVAX."


Chain_Full_2="Ethereum Mainnet"
Chain_Common_2="Ethereum"
Chain_cBridge_2="Ethereum Mainnet"
Chain_Common_the_2="an"
Chain_Info2=""
Chain_Info2_ChainId=1
Chain_Info2_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "

