stepImgName="seo_Kava_Ethereum"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_1="Kava Network"
Chain_Common_1="Kava"
Chain_cBridge_1="Kava EVM Co-Chain"
Chain_Common_the_1="a"
Chain_Info1=""
Chain_Info1_ChainId=2222
Chain_Info1_Description="Empowering the next wave of developers in creating the next generation of blockchain technology, the Kava Network is a Layer-1 blockchain that combines the speed and scalability of the Cosmos SDK with the developer support of Ethereum through its unique co-chain architecture. Kava focuses on interoperability to bring together the Ethereum and Cosmos Co-Chain ecosystems, while optimizing the scalability to enable less friction for the flow of users, assets, and projects alike—as it is powered by the Tendermint Core consensus engine. <br><br>KAVA is the governance token of the Kava Network and can also be staked by validators or delegated to validator nodes. Stakers and delegators earn a portion of the network's fees as a reward for securing the network and also have voting rights in network governance proposals."
Chain_Info1_TokenFull="Kava"
Chain_Info1_TokenTicker="KAVA"
Chain_Info1_BridgedTokenTicker=""
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/chain-icon/kava.png"
Chain_Info1_Token_AssetFullName="Kava"
Chain_Info1_Token_TradingSymbol="KAVA"
Chain_Info1_Token_PriceSymbol="KAVA"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://www.coingecko.com/en/coins/kava"
Chain_Info1_Token_Description1="The Kava protocol facilitates a peer-to-peer lending protocol where users can lock their funds in smart contracts. Then those contracts mint new USDX tokens that users can take as a loan based on collateral. Much like other blockchains, Kava’s native token, KAVA, is utilized to facilitate governance voting to help guide the network upgrades and enhancements, including parameters related to collateralized debt positioning system. The token is used additionally to help maintain the network’s security by allowing holders to validate blocks and stake on various applications. <br><br>With a function to serve as a reserve, the network will mint new KAVA to utilize in the purchase of USDX if USDX becomes over collateralized, allowing Kava to ensure its stablecoin retains its value.<br><br>Celer’s cross-chain bridge, cBridge, supports the cross-chain bridging of KAVA <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/chain-icon/kava.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Kava token and the ticker of this asset is KAVA."



Chain_Full_2="Ethereum Mainnet"
Chain_Common_2="Ethereum"
Chain_cBridge_2="Ethereum Mainnet"
Chain_Info2=""
Chain_Info2_ChainId=1
Chain_Info2_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "

