stepImgName="seo_Ethereum_Arbitrum"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "


Chain_Full_1="Ethereum Mainnet"
Chain_Common_1="Ethereum"
Chain_cBridge_1="Ethereum Mainnet"
Chain_Info1=""
Chain_Info1_ChainId=1
Chain_Info1_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info1_TokenFull="Ether"
Chain_Info1_TokenTicker="ETH"
Chain_Info1_BridgedTokenTicker="WETH"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2="Ethereum"
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info1_Token_AssetFullName="Ether"
Chain_Info1_Token_TradingSymbol="ETH"
Chain_Info1_Token_PriceSymbol="ETH"
Chain_Info1_Token_PriceUSD="1,221.61"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info1_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_2="Arbitrum"
Chain_Common_2="Arbitrum"
Chain_cBridge_2="Arbitrum One"
Chain_Common_the_2="an"
Chain_Info2=""
Chain_Info2_ChainId=42161
Chain_Info2_Description="Arbitrum is a layer 2 solution for Ethereum supporting dApps by aiming to bring scalability and affordable transactions for Ethereum network users. To enable this, Arbitrum uses “Optimistic Rollup,” meaning Arbitrum allows every validator to post a rollup block that they claim is correct with a 7 day window to dispute this block as there is complete transparency of transactions. An optimistic rollup executes transactions on layer 2 and then submits the transaction data to layer 1, in this case to the Ethereum Mainnet. Since Arbitrum is interacting with the Ethereum Mainnet, all transaction fees are paid in Ethereum.<br><br>When making asset withdrawals from Arbitrum to Ethereum Mainnet, cBridge offers the finality within 5~20 minutes and delivers this at 50% less gas fees than the native bridge."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH."
