stepImgName="seo_Ethereum_Flow"
indexType="two_wallet"

TokenFull="Tether"
TokenTicker="USDT"
BridgedTokenTicker=""
TokenAKA_1=""
TokenAKA_2=""
Token_Icon="https://get.celer.app/cbridge-icons/USDT.png"
TokenInfo=""
TokenInfo_AssetFullName="Tether"
TokenInfo_TradingSymbol="USDT"
TokenInfo_PriceSymbol="USDT"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/USDT.png"
TokenInfo_PriceUSD="0.00"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/tether/"
TokenInfo_Description1="Tether, also commonly referred to as <a href='https://tether.to/en/' class='a-config' target='_blank'>USDT</a>, is a popular stablecoin often used by investors who want to avoid volatility while holding funds within the cryptocurrency ecosystem. Much like the other popular stablecoin, USD Coin, more commonly known as USDC, USDT is also native to the internet and can be used similarly - holding in crypto wallets, making purchases, trading, etc. Since USDT is pegged to a traditional FIAT currency, it’s often backed by collateralized reserves made entirely or mostly of the pegged currency to avoid volatility of value.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of USDT <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/USDT.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Tether and the ticker of this asset is USDT."


Chain_Full_1="Ethereum Mainnet"
Chain_Common_1="Ethereum"
Chain_cBridge_1="Ethereum Mainnet"
Chain_Info1=""
Chain_Info1_ChainId=1
Chain_Info1_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info1_TokenFull="Ether"
Chain_Info1_TokenTicker="ETH"
Chain_Info1_BridgedTokenTicker="WETH"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2="Ethereum"
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info1_Token_AssetFullName="Ether"
Chain_Info1_Token_TradingSymbol="ETH"
Chain_Info1_Token_PriceSymbol="ETH"
Chain_Info1_Token_PriceUSD="1,221.61"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info1_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_2="Flow"
Chain_Common_2="Flow"
Chain_cBridge_2="Flow Mainnet"
Chain_Common_the_2="a"
Chain_Info2=""
Chain_Info2_ChainId=12340001
Chain_Info2_Description="Created by Dapper Labs in 2020, the Flow blockchain was designed to support gaming with a focus on supporting the NFTs often associated with gaming and sports. This includes supporting larger ventures such as NBA Top Shot, UFC, and many others. The Flow is based on a unique multi-role architecture and is designed to scale without sharding. This enables fast, low cost transactions in order to help facilitate adoption for the masses and allows for improvements in speed and throughput while preserving a developer-friendly, ACID-compliant, environment.<br><br>FLOW is the native token on the Flow blockchain and is used to support activities on the Flow network similar to how ETH is used on Ethereum including for collateralizing, minting, medium of exchange and payment as well as for validating."
Chain_Info2_TokenFull="Flow"
Chain_Info2_TokenTicker="FLOW"
Chain_Info2_BridgedTokenTicker=""
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/FLOW.png"
Chain_Info2_Token_AssetFullName="Flow"
Chain_Info2_Token_TradingSymbol="FLOW"
Chain_Info2_Token_PriceSymbol="FLOW"
Chain_Info2_Token_PriceUSD="0.00"
Chain_Info2_Token_PriceLink="https://www.coingecko.com/en/coins/flow"
Chain_Info2_Token_Description1="Like many other blockchains, the FLOW token is the native currency of the Flow blockchain and is used as currency throughout all applications created within the Flow ecosystem, which includes covering for transaction fees (gas), governance voting, medium of exchange, validators to keep the network secure, developers, deposit for storing data, and on decentralized application (dApp) throughout out the Flow ecosystem. <br><br>Celer’s cross-chain bridge, cBridge, supports the cross-chain bridging of FLOW <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/FLOW.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Flow token and the ticker of this asset is FLOW."
