stepImgName="seo_Arbitrum_Polygon"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. "
TokenInfo_Description2="Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH."


Chain_Full_1="Arbitrum"
Chain_Common_1="Arbitrum"
Chain_cBridge_1="Arbitrum One"
Chain_Info1=""
Chain_Info1_ChainId=42161
Chain_Info1_Description="Arbitrum is a layer 2 solution for Ethereum supporting dApps by aiming to bring scalability and affordable transactions for Ethereum network users. To enable this, Arbitrum uses “Optimistic Rollup,” meaning Arbitrum allows every validator to post a rollup block that they claim is correct with a 7 day window to dispute this block as there is complete transparency of transactions. An optimistic rollup executes transactions on layer 2 and then submits the transaction data to layer 1, in this case to the Ethereum Mainnet. Since Arbitrum is interacting with the Ethereum Mainnet, all transaction fees are paid in Ethereum.<br><br>When making asset withdrawals from Arbitrum to Ethereum Mainnet, cBridge offers the finality within 5~20 minutes and delivers this at 50% less gas fees than the native bridge."
Chain_Info1_TokenFull="Ether"
Chain_Info1_TokenTicker="ETH"
Chain_Info1_BridgedTokenTicker="WETH"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2="Ethereum"
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info1_Token_AssetFullName="Ether"
Chain_Info1_Token_TradingSymbol="ETH"
Chain_Info1_Token_PriceSymbol="ETH"
Chain_Info1_Token_PriceUSD="1,221.61"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info1_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_2="Polygon"
Chain_Common_2="Polygon"
Chain_cBridge_2="Polygon"
Chain_Common_the_2="a"
Chain_Info2=""
Chain_Info2_ChainId=137
Chain_Info2_Description="Polygon is a layer-2 network that aims to be a scaling solution that provides multiple tools to improve the speed, reduce cost, and reduce the complexity of transactions and transfers on more congested and expensive blockchains like Ethereum. As a layer-2 network, Polygon acts as an add-on layer to Ethereum that isn’t looking to change the original blockchain layer. Polygon wishes to help enable Ethereum to expand in size, security, efficiency, and usefulness. All while seeking to spur developers to bring enticing products to market. The token underpinning the network is called MATIC and is used as the unit of payment and settlement between participants who interact within Polygon."
Chain_Info2_TokenFull="MATIC"
Chain_Info2_TokenTicker="MATIC"
Chain_Info2_BridgedTokenTicker=""
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/MATIC.png"
Chain_Info2_Token_AssetFullName="MATIC"
Chain_Info2_Token_TradingSymbol="MATIC"
Chain_Info2_Token_PriceSymbol="MATIC"
Chain_Info2_Token_PriceUSD="0.4496"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/polygon/"
Chain_Info2_Token_Description1="MATIC is the native cryptocurrency of the <a href='https://polygon.technology/' class='a-config' target='_blank'>Polygon</a> network and is used to help drive development across the network and can be used for staking and paying for transaction fees. Simply put, it is the currency of Polygon and the applications running on it. Whether you want to simply transfer some MATIC between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Polygon; anytime you interact with Polygon you will be required to pay a small fee in MATIC. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of MATIC  <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/MATIC.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is MATIC and the ticker of this asset is MATIC."

