stepImgName="seo_Astar_Ethereum"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH."


Chain_Full_1="Astar Network"
Chain_Common_1="Astar"
Chain_cBridge_1="Astar"
Chain_Common_the_1="a"
Chain_Info1=""
Chain_Info1_ChainId=592
Chain_Info1_Description="Rebranding itself from Plasma to Astar Network in 2021 with a greater vision to support its ecosystem, Astar Network is a multiple blockchain dApp hub that offers dApps staking, L2 solutions, and a cross virtual machine that supports EVMs.<br><br>Astar Network is composed of several major components working together including Polkadot, to facilitate cross chain communication. Astar is considered the Polkadot version of Shiden Network for Kusama. Parachains are also used to connect independent blockchains to the Polkadot ecosystem. Astar also supports crowd loans to help fundraise for a parachain slot within the Polkadot ecosystem. <br><br>ASTR token is the native and governance token of the Astar Network. ASTR tokens are used for staking directly on Astar dApps.  "
Chain_Info1_TokenFull="ASTAR"
Chain_Info1_TokenTicker="ASTR"
Chain_Info1_BridgedTokenTicker=""
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/chain-icon/Astar.png"
Chain_Info1_Token_AssetFullName="ASTAR"
Chain_Info1_Token_TradingSymbol="ASTR"
Chain_Info1_Token_PriceSymbol="ASTR"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://www.coingecko.com/en/coins/astar"
Chain_Info1_Token_Description1="Similar to many popular blockchains, ASTR is the native token for the Astar Network for transaction on-chain fees. The ASTR token has 3 other utilities including (1). Facilitating governance activities like voting and referenda, (2). Staking on different decentralized applications and the network itself, while earning ASTR tokens as rewards, (3) layer 2 networks and applications can deposit ASTR on their respective Layer 1s in creating layer 2 applications that can support omnichain general message and liquidity passing.<br><br>Celer’s cross-chain bridge, cBridge, supports the cross-chain bridging of AST <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/chain-icon/Astar.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is ASTAR and the ticker of this asset is AST."



Chain_Full_2="Ethereum Mainnet"
Chain_Common_2="Ethereum"
Chain_cBridge_2="Ethereum Mainnet"
Chain_Info2=""
Chain_Info2_ChainId=1
Chain_Info2_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "

