stepImgName="seo_Binance_Polygon"
indexType="one_wallet"

TokenFull="BNB"
TokenTicker="BNB"
BridgedTokenTicker="muxBNB"
TokenAKA_1=""
TokenAKA_2=""
Token_Icon="https://get.celer.app/cbridge-icons/BNB.png"
TokenInfo=""
TokenInfo_AssetFullName="BNB"
TokenInfo_TradingSymbol="BNB"
TokenInfo_PriceSymbol="BNB"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/BNB.png"
TokenInfo_PriceUSD="0.00"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/bnb/"
TokenInfo_Description1="BNB is the native cryptocurrency token that fuels the <a href='https://www.bnbchain.org/en' class='a-config' target='_blank'>BNB Chain</a> ecosystem and serves as a governance and utility token fueling transactions on the BNB Chain, similar to gas on Ethereum. <br><br>Whether you want to simply transfer some BNB between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone has built on BNB; anytime you interact with BNB Chain you will be required to pay a small fee in BNB. BNB can be traded like other cryptocurrencies and widely used in various apps and use cases, including reducing Binance exchange trading fees, paying for transaction fees made via the BNB Chain, and purchasing goods and services online and in-store. <br><br>With many large-scale applications in Metaverse, GameFi, SocialFi and others being incorporated into the BNB Chain, Binance is positioning BNB as a token for the Binance ecosystem, which serves several sectors.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of BNB <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/BNB.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is BNB and the ticker of this asset is BNB."


Chain_Full_1="BNB Chain"
Chain_Common_1="Binance"
Chain_cBridge_1="BNB Chain"
Chain_Info1=""
Chain_Info1_ChainId=56
Chain_Info1_Description="The BNB Chain, often referred to as Binance Smart Chain (BSC) or the Binance Chain, is composed of both the BSC and Binance Chain combined. The BNB Chain (abbreviation for “Build, ‘N Build”) enables BNB Chain governance for things like staking and voting.It also remains Ethereum Virtual Machine (EVM) compatible. The BNB Chain aims to increase interoperability across the blockchain ecosystem and develop the core infrastructure to enable and connect the “world’s parallel virtual environment.” With more new and improved features than its two separate parts, the BNB Chain has a boosted BSC throughout, is able to introduce an on-chain governance mechanism, have one-to-many chain scaling, and has overall improved scaling solutions. Plus  it has expanded the number of BSC validator sets from 21 to 41!<br><br>The six key pillars of the BNB Chain include being permissionless, decentralized, open, multichain accessible, designed for creators and inventors, and with the goal to be bigger than Binance itself."
Chain_Info1_TokenFull="BNB"
Chain_Info1_TokenTicker="BNB"
Chain_Info1_BridgedTokenTicker="muxBNB"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/BNB.png"
Chain_Info1_Token_AssetFullName="BNB"
Chain_Info1_Token_TradingSymbol="BNB"
Chain_Info1_Token_PriceSymbol="BNB"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/bnb/"
Chain_Info1_Token_Description1="BNB is the native cryptocurrency token that fuels the <a href='https://www.bnbchain.org/en' class='a-config' target='_blank'>BNB Chain</a> ecosystem and serves as a governance and utility token fueling transactions on the BNB Chain, similar to gas on Ethereum. <br><br>Whether you want to simply transfer some BNB between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone has built on BNB; anytime you interact with BNB Chain you will be required to pay a small fee in BNB. BNB can be traded like other cryptocurrencies and widely used in various apps and use cases, including reducing Binance exchange trading fees, paying for transaction fees made via the BNB Chain, and purchasing goods and services online and in-store. <br><br>With many large-scale applications in Metaverse, GameFi, SocialFi and others being incorporated into the BNB Chain, Binance is positioning BNB as a token for the Binance ecosystem, which serves several sectors. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of BNB <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/BNB.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is BNB and the ticker of this asset is BNB."



Chain_Full_2="Polygon"
Chain_Common_2="Polygon"
Chain_cBridge_2="Polygon"
Chain_Common_the_2="a"
Chain_Info2=""
Chain_Info2_ChainId=137
Chain_Info2_Description="Polygon is a layer-2 network that aims to be a scaling solution that provides multiple tools to improve the speed, reduce cost, and reduce the complexity of transactions and transfers on more congested and expensive blockchains like Ethereum. As a layer-2 network, Polygon acts as an add-on layer to Ethereum that isn’t looking to change the original blockchain layer. Polygon wishes to help enable Ethereum to expand in size, security, efficiency, and usefulness. All while seeking to spur developers to bring enticing products to market. The token underpinning the network is called MATIC and is used as the unit of payment and settlement between participants who interact within Polygon."
Chain_Info2_TokenFull="MATIC"
Chain_Info2_TokenTicker="MATIC"
Chain_Info2_BridgedTokenTicker=""
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/MATIC.png"
Chain_Info2_Token_AssetFullName="MATIC"
Chain_Info2_Token_TradingSymbol="MATIC"
Chain_Info2_Token_PriceSymbol="MATIC"
Chain_Info2_Token_PriceUSD="0.4496"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/polygon/"
Chain_Info2_Token_Description1="MATIC is the native cryptocurrency of the <a href='https://polygon.technology/' class='a-config' target='_blank'>Polygon</a> network and is used to help drive development across the network and can be used for staking and paying for transaction fees. Simply put, it is the currency of Polygon and the applications running on it. Whether you want to simply transfer some MATIC between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Polygon; anytime you interact with Polygon you will be required to pay a small fee in MATIC. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of MATIC  <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/MATIC.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is MATIC and the ticker of this asset is MATIC."
