stepImgName="seo_Binance_Avalanche"
indexType="one_wallet"

TokenFull="BNB"
TokenTicker="BNB"
BridgedTokenTicker="muxBNB"
TokenAKA_1=""
TokenAKA_2=""
Token_Icon="https://get.celer.app/cbridge-icons/BNB.png"
TokenInfo=""
TokenInfo_AssetFullName="BNB"
TokenInfo_TradingSymbol="BNB"
TokenInfo_PriceSymbol="BNB"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/BNB.png"
TokenInfo_PriceUSD="0.00"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/bnb/"
TokenInfo_Description1="BNB is the native cryptocurrency token that fuels the <a href='https://www.bnbchain.org/en' class='a-config' target='_blank'>BNB Chain</a> ecosystem and serves as a governance and utility token fueling transactions on the BNB Chain, similar to gas on Ethereum. <br><br>Whether you want to simply transfer some BNB between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone has built on BNB; anytime you interact with BNB Chain you will be required to pay a small fee in BNB. BNB can be traded like other cryptocurrencies and widely used in various apps and use cases, including reducing Binance exchange trading fees, paying for transaction fees made via the BNB Chain, and purchasing goods and services online and in-store. <br><br>With many large-scale applications in Metaverse, GameFi, SocialFi and others being incorporated into the BNB Chain, Binance is positioning BNB as a token for the Binance ecosystem, which serves several sectors.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of BNB <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/BNB.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is BNB and the ticker of this asset is BNB."


Chain_Full_1="BNB Chain"
Chain_Common_1="Binance"
Chain_cBridge_1="BNB Chain"
Chain_Info1=""
Chain_Info1_ChainId=56
Chain_Info1_Description="The BNB Chain, often referred to as Binance Smart Chain (BSC) or the Binance Chain, is composed of both the BSC and Binance Chain combined. The BNB Chain (abbreviation for “Build, ‘N Build”) enables BNB Chain governance for things like staking and voting.It also remains Ethereum Virtual Machine (EVM) compatible. The BNB Chain aims to increase interoperability across the blockchain ecosystem and develop the core infrastructure to enable and connect the “world’s parallel virtual environment.” With more new and improved features than its two separate parts, the BNB Chain has a boosted BSC throughout, is able to introduce an on-chain governance mechanism, have one-to-many chain scaling, and has overall improved scaling solutions. Plus  it has expanded the number of BSC validator sets from 21 to 41!<br><br>The six key pillars of the BNB Chain include being permissionless, decentralized, open, multichain accessible, designed for creators and inventors, and with the goal to be bigger than Binance itself."
Chain_Info1_TokenFull="BNB"
Chain_Info1_TokenTicker="BNB"
Chain_Info1_BridgedTokenTicker="muxBNB"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/BNB.png"
Chain_Info1_Token_AssetFullName="BNB"
Chain_Info1_Token_TradingSymbol="BNB"
Chain_Info1_Token_PriceSymbol="BNB"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/bnb/"
Chain_Info1_Token_Description1="BNB is the native cryptocurrency token that fuels the <a href='https://www.bnbchain.org/en' class='a-config' target='_blank'>BNB Chain</a> ecosystem and serves as a governance and utility token fueling transactions on the BNB Chain, similar to gas on Ethereum. <br><br>Whether you want to simply transfer some BNB between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone has built on BNB; anytime you interact with BNB Chain you will be required to pay a small fee in BNB. BNB can be traded like other cryptocurrencies and widely used in various apps and use cases, including reducing Binance exchange trading fees, paying for transaction fees made via the BNB Chain, and purchasing goods and services online and in-store. <br><br>With many large-scale applications in Metaverse, GameFi, SocialFi and others being incorporated into the BNB Chain, Binance is positioning BNB as a token for the Binance ecosystem, which serves several sectors.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of BNB <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/BNB.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is BNB and the ticker of this asset is BNB."

Chain_Full_2="Avalanche Network"
Chain_Common_2="Avalanche"
Chain_cBridge_2="Avalanche"
Chain_Common_the_2="an"
Chain_Info2=""
Chain_Info2_ChainId=43114
Chain_Info2_Description="Avalanche, as a layer one blockchain, is an open programmable smart contracts platform for decentralized applications. Similar to other layer one blockchains, Avalanche supports a wide spectrum of applications related to DeFi, gaming, NFTs, the metaverse, as well as support for stablecoins. Avalanche is composed of three key components that make up the blockchain: (1). The Platform Chain (P-Chain) which coordinates validators and the creation of subnets, (2). the C-Chain for the creation of smart contracts, and (3). the X-Chain for managing and exchanging assets.<br><br>As an Ethereum Virtual Machine (EVM) compatible platform, applications that are built using the Ethereum programming language Solidity are also able to be deployed on Avalanche with minimal modifications. This enables developers from one of the largest and widely adopted blockchain communities to build on Avalanche and to deploy custom private or public blockchains as “subnets.”"
Chain_Info2_TokenFull="Avalanche"
Chain_Info2_TokenTicker="AVAX"
Chain_Info2_BridgedTokenTicker="muxAVAX"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/AVAX.png"
Chain_Info2_Token_AssetFullName="Avalanche"
Chain_Info2_Token_TradingSymbol="AVAX"
Chain_Info2_Token_PriceSymbol="AVAX"
Chain_Info2_Token_PriceUSD="0.00"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/avalanche/"
Chain_Info2_Token_Description1="AVAX is the native cryptocurrency of <a href='https://www.avax.network/' class='a-config' target='_blank'>Avalanche</a> with 720 million AVAX coins in circulation.  AVAX is used to help drive development across the network and can be used for staking and paying for transaction fees. It can also be used in proposing and voting on future network upgrades. In other words, AVAX is the currency of Avalanche and the applications running on it. Whether you want to simply transfer some AVAX between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Avalanche; anytime you interact with Avalanche you will be required to pay a small fee in AVAX.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of AVAX <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/AVAX.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Avalanche and the ticker of this asset is AVAX."
