stepImgName="seo_Klaytn_Ethereum"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_1="Klaytn"
Chain_Common_1="Klaytn"
Chain_cBridge_1="Klaytn"
Chain_Common_the_1="a"
Chain_Info1=""
Chain_Info1_ChainId=8217
Chain_Info1_Description="With the goal of becoming the primary platform for DeFi and NFTs in the Asia market, Klaytn was developed by the team at Ground X, which develops and oversees the blockchain technology of one of Korea’s largest Web 2 companies, Kakao. Klaytn’s Mainnet, Cypress, has been clocked with a high throughput of up to 4,000 transactions per second with one-second block generation intervals and immediate transaction finality. <br><br>KLAY is the native utility token of the Klaytn Network, and is used for network transactions similar to ETH on Ethereum, including minting NFTs and yield farming to earn staking rewards."
Chain_Info1_TokenFull="Klaytn"
Chain_Info1_TokenTicker="KLAY"
Chain_Info1_BridgedTokenTicker=""
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/chain-icon/klaytn.png"
Chain_Info1_Token_AssetFullName="Klaytn"
Chain_Info1_Token_TradingSymbol="KLAY"
Chain_Info1_Token_PriceSymbol="KLAY"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://www.coingecko.com/en/coins/klaytn"
Chain_Info1_Token_Description1="The KLAY token is the native token of the Klaytn Blockchain and a network of blockchain applications (so-called BApps) that operate across the Klaytn blockchain. Similar to other blockchains. KLAY is used to pay for transaction fees and used for staking for rewards. Additionally, the KLAY token is used as a medium of exchange across the various BApps in the Klaytn ecosystem.<br><br>With deep roots with South Korea’ s popular social media giant, KakaoTalk, KLAY is integrated with a number of applications including crypto wallets and a growing list of applications that power the Klayten ecosystem. KLAY is also used to encourage participation through the Klaytn Improvement Reserve (KIR), a reward-based system that utilizes the KLAY token to incentivize commitment to maintaining the growth of the Klaytn ecosystem, namely - submitting proposals, improving user and developer experiences and other activities that support the ecosystem.<br><br>Celer’s cross-chain bridge, cBridge, supports the cross-chain bridging of KLAY <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/chain-icon/klaytn.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Klaytn token and the ticker of this asset is KLAY. "



Chain_Full_2="Ethereum Mainnet"
Chain_Common_2="Ethereum"
Chain_cBridge_2="Ethereum Mainnet"
Chain_Info2=""
Chain_Info2_ChainId=1
Chain_Info2_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "

