stepImgName="seo_Ethereum_Optimism"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH.  "


Chain_Full_1="Ethereum Mainnet"
Chain_Common_1="Ethereum"
Chain_cBridge_1="Ethereum Mainnet"
Chain_Info1=""
Chain_Info1_ChainId=1
Chain_Info1_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info1_TokenFull="Ether"
Chain_Info1_TokenTicker="ETH"
Chain_Info1_BridgedTokenTicker="WETH"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2="Ethereum"
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info1_Token_AssetFullName="Ether"
Chain_Info1_Token_TradingSymbol="ETH"
Chain_Info1_Token_PriceSymbol="ETH"
Chain_Info1_Token_PriceUSD="1,221.61"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info1_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_2="Optimism"
Chain_Common_2="Optimism"
Chain_cBridge_2="Optimism"
Chain_Common_the_2="an"
Chain_Info2=""
Chain_Info2_ChainId=10
Chain_Info2_Description="Optimism is a popular layer 2 scaling solution for Ethereum similar to Arbitrum that can support all of Ethereum’s dApps. To enable efficient scaling, instead of  running all computation on the Ethereum Mainnet, Optimism puts all transaction data on-chain but runs computation off-chain. This effectively increases Ethereum’s transactions per second and decreases transaction fees. ETH or Ether is the standard currency used to pay for transactions on Optimism where you can use ETH to pay for transactions on L1, and you use it to pay for transactions on Optimism, L2. Optimism also has its governance token Optimism with the ticker symbol OP.<br><br>When making asset withdrawals from Optimism to Ethereum Mainnet, cBridge offers the finality within 5~20 minutes and delivers this at 50% less gas fees than the native bridge."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH."
