stepImgName="seo_Nervos_Ethereum"
indexType="one_wallet"

TokenFull="Ether"
TokenTicker="ETH"
BridgedTokenTicker="WETH"
TokenAKA_1=""
TokenAKA_2="Ethereum"
Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo=""
TokenInfo_AssetFullName="Ether"
TokenInfo_TradingSymbol="ETH"
TokenInfo_PriceSymbol="ETH"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/ETH.png"
TokenInfo_PriceUSD="1,221.61"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
TokenInfo_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH. <br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "



Chain_Full_1="Nervos Godwoken"
Chain_Common_1="Nervos Godwoken"
Chain_cBridge_1="Nervos Godwoken"
Chain_Common_the_1="a"
Chain_Info1=""
Chain_Info1_ChainId=71402
Chain_Info1_Description="Nervos Godwoken is the Layer 2 of Nervos and its solution to support the EVM ecosystem. This EVM-compatible Optimistic Roll-up was designed to enable quick and easy dApp development. The Nervos Layer 1 is a public blockchain that provides the security and decentralization for the Nervos platform, while generating trust and extending to multiple blockchain layers promoting flexibility and scalability. Godwoken is, by nature, a multi-chain solution that leverages advanced account abstraction enabling flexible wallet support and traditional user experience similar to Web 2.<br><br>Similar to the relationship between ETH and Etherreum, CKB, the token used on Nervos Godwoken, is used in executing your smart contracts or for use in dApps and even in renting out space on the blockchain. It can also be used as a medium of exchange and as a store of value."
Chain_Info1_TokenFull="Nervos"
Chain_Info1_TokenTicker="CKB"
Chain_Info1_BridgedTokenTicker=""
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/chain-icon/nervos.png"
Chain_Info1_Token_AssetFullName="CKB"
Chain_Info1_Token_TradingSymbol="CKB"
Chain_Info1_Token_PriceSymbol="pCKB"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://www.coingecko.com/en/coins/nervos-network"
Chain_Info1_Token_Description1="<a href='https://github.com/godwokenrises/godwoken/blob/develop/docs/life_of_a_polyjuice_transaction.md#pckb' class='a-config' target='_blank'>pCKB</a> is an erc20 representation of CKB on L2. Deployed on the Godwoken chain, it is the new concept that Godwoken v1 introduced, and its value is pegged to Nervos' native token (CKByte or CKB). This means the value of pCKB is the same as the value of CKB. pCKB’s role on Godwoken is similar to that of ETH’s role on Ethereum where it is used to collect transaction fees, and even allows developers and users to claim storage space on the Nervos blockchain in proportion to their holdings. <br><br>While different Godwoken chains may use different token types as pCKB, the Godwoken chain uses CKB as pCKB by default, pCKB, as the unit for calculating transaction fees in Godwoken, has a similar calculating method for transaction fees to that of Ethereum. Click <a href='https://docs.godwoken.io/fastWithdrawal' class='a-config' target='_blank'>here</a> for more information about pCKB."



Chain_Full_2="Ethereum Mainnet"
Chain_Common_2="Ethereum"
Chain_cBridge_2="Ethereum Mainnet"
Chain_Info2=""
Chain_Info2_ChainId=1
Chain_Info2_Description="Ethereum is a decentralized blockchain platform that provides open access to digital money and data-friendly services. It is a community-built technology that is responsible for Ether (ETH) also referred to as Ethereum, as well as many different decentralized applications (dApps) that many people use today. With their tools and unique programming language, Solidity, Ethereum’s users can create, publish, monetize, and use applications on the platform, while using its Ether (ETH) cryptocurrency as payment. Ethereum allows you to move money, or make agreements, directly with someone else while serving as a decentralized public ledger for verifying and recording those transactions."
Chain_Info2_TokenFull="Ether"
Chain_Info2_TokenTicker="ETH"
Chain_Info2_BridgedTokenTicker="WETH"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2="Ethereum"
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/ETH.png"
Chain_Info2_Token_AssetFullName="Ether"
Chain_Info2_Token_TradingSymbol="ETH"
Chain_Info2_Token_PriceSymbol="ETH"
Chain_Info2_Token_PriceUSD="1,221.61"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/ethereum/"
Chain_Info2_Token_Description1="Ether (<a href='https://ethereum.org/en/eth/' class='a-config' target='_blank'>ETH</a>), also referred to as Ethereum, is the main decentralized cryptocurrency used when dealing with <a href='https://ethereum.org/en/' class='a-config' target='_blank'>Ethereum Mainnet</a> and its various layer-2s like Arbitrum and Optimism. Simply put, it is the currency of when interacting with Ethereum Mainnet or its layer-2s. Whether you want to simply transfer some ETH between wallets, use ETH as collateral for creating an entirely new token, receive some bridged tokens from another chain like Polygon, or use an application someone had built on Ethereum; anytime you interact with Ethereum you will be required to pay a small fee in ETH.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of Ether (ETH) <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/ETH.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Ether and the ticker of this asset is ETH. "

