stepImgName="seo_Avalanche_Fantom"
indexType="one_wallet"

TokenFull="Avalanche"
TokenTicker="AVAX"
BridgedTokenTicker="muxAVAX"
TokenAKA_1=""
TokenAKA_2=""
Token_Icon="https://get.celer.app/cbridge-icons/AVAX.png"
TokenInfo=""
TokenInfo_AssetFullName="Avalanche"
TokenInfo_TradingSymbol="AVAX"
TokenInfo_PriceSymbol="AVAX"
TokenInfo_TradingIcon="https://get.celer.app/cbridge-icons/AVAX.png"
TokenInfo_PriceUSD="0.00"
TokenInfo_PriceLink="https://coinmarketcap.com/currencies/avalanche/"
TokenInfo_Description1="AVAX is the native cryptocurrency of <a href='https://www.avax.network/' class='a-config' target='_blank'>Avalanche</a> with 720 million AVAX coins in circulation.  AVAX is used to help drive development across the network and can be used for staking and paying for transaction fees. It can also be used in proposing and voting on future network upgrades. In other words, AVAX is the currency of Avalanche and the applications running on it. Whether you want to simply transfer some AVAX between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Avalanche; anytime you interact with Avalanche you will be required to pay a small fee in AVAX.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of AVAX <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/AVAX.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Avalanche and the ticker of this asset is AVAX."


Chain_Full_1="Avalanche Network"
Chain_Common_1="Avalanche"
Chain_cBridge_1="Avalanche"
Chain_Info1=""
Chain_Info1_ChainId=43114
Chain_Info1_Description="Avalanche, as a layer one blockchain, is an open programmable smart contracts platform for decentralized applications. Similar to other layer one blockchains, Avalanche supports a wide spectrum of applications related to DeFi, gaming, NFTs, the metaverse, as well as support for stablecoins. Avalanche is composed of three key components that make up the blockchain: (1). The Platform Chain (P-Chain) which coordinates validators and the creation of subnets, (2). the C-Chain for the creation of smart contracts, and (3). the X-Chain for managing and exchanging assets.<br><br>As an Ethereum Virtual Machine (EVM) compatible platform, applications that are built using the Ethereum programming language Solidity are also able to be deployed on Avalanche with minimal modifications. This enables developers from one of the largest and widely adopted blockchain communities to build on Avalanche and to deploy custom private or public blockchains as “subnets.”"
Chain_Info1_TokenFull="Avalanche"
Chain_Info1_TokenTicker="AVAX"
Chain_Info1_BridgedTokenTicker="muxAVAX"
Chain_Info1_TokenAKA_1=""
Chain_Info1_TokenAKA_2=""
Chain_Info1_Token_Icon="https://get.celer.app/cbridge-icons/AVAX.png"
Chain_Info1_Token_AssetFullName="Avalanche"
Chain_Info1_Token_TradingSymbol="AVAX"
Chain_Info1_Token_PriceSymbol="AVAX"
Chain_Info1_Token_PriceUSD="0.00"
Chain_Info1_Token_PriceLink="https://coinmarketcap.com/currencies/avalanche/"
Chain_Info1_Token_Description1="AVAX is the native cryptocurrency of <a href='https://www.avax.network/' class='a-config' target='_blank'>Avalanche</a> with 720 million AVAX coins in circulation.  AVAX is used to help drive development across the network and can be used for staking and paying for transaction fees. It can also be used in proposing and voting on future network upgrades. In other words, AVAX is the currency of Avalanche and the applications running on it. Whether you want to simply transfer some AVAX between wallets, receive some bridged tokens from another chain like Ethereum Mainnet, or use an application someone had built on Avalanche; anytime you interact with Avalanche you will be required to pay a small fee in AVAX.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of AVAX <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/AVAX.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Avalanche and the ticker of this asset is AVAX."



Chain_Full_2="Fantom"
Chain_Common_2="Fantom"
Chain_cBridge_2="Fantom"
Chain_Common_the_2="a"
Chain_Info2=""
Chain_Info2_ChainId=250
Chain_Info2_Description="Fantom, a layer 1 blockchain, is a “high-performance, scalable, EVM-compatible, and secure smart-contract platform.” With over 200 dApps launched on the Fantom mainnet, Fantom’s consensus mechanism, Lachesis, enables the delivery of fast transaction speeds, low transaction costs, and deterministic finality, while remaining permissionless, decentralized, and open-source.<br><br>Similar to other Ethereum Virtual Machine (EVM) compatible platforms, applications that are built using Solidity, the Ethereum programming language, developers can deploy on Fantom with minimal modifications. Fantom envisions a more connected and efficient blockchain ecosystem and is expanding its blockchain technology footprint."
Chain_Info2_TokenFull="Fantom"
Chain_Info2_TokenTicker="FTM"
Chain_Info2_BridgedTokenTicker="muxFTM"
Chain_Info2_TokenAKA_1=""
Chain_Info2_TokenAKA_2=""
Chain_Info2_Token_Icon="https://get.celer.app/cbridge-icons/FTM.png"
Chain_Info2_Token_AssetFullName="FANTOM"
Chain_Info2_Token_TradingSymbol="FTM"
Chain_Info2_Token_PriceSymbol="FTM"
Chain_Info2_Token_PriceUSD="0.00"
Chain_Info2_Token_PriceLink="https://coinmarketcap.com/currencies/fantom/"
Chain_Info2_Token_Description1="FTM is the primary token on the <a href='https://fantom.foundation/' class='a-config' target='_blank'>Fantom</a> network, and is used for securing the network (as the main utility token) through staking, for governance, for payments, and for fees. With a total supply of 3.175 billion FTM tokens, FTM is available as native mainnet tokens, as ERC-20 tokens, and as BEP-2 tokens.<br><br>Our cross-chain bridge, cBridge, supports the cross-chain bridging of FTM <span><img class='describe-img' src='https://get.celer.app/cbridge-icons/FTM.png' alt=''/></span> between multiple chains with the fastest speeds, lowest costs, and most secure transactions available. The full name of this asset is Fantom and the ticker of this asset is FTM."

