/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CommonOwnerProxy,
  CommonOwnerProxyInterface,
} from "../CommonOwnerProxy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newOwner",
        type: "uint256",
      },
    ],
    name: "TransferOwnershipProposalCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum OwnerDataTypes.Action",
        name: "action",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "UpdatePauserProposalCreated",
    type: "event",
  },
  {
    inputs: [],
    name: "gov",
    outputs: [
      {
        internalType: "contract SimpleGovernance",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract SimpleGovernance",
        name: "_gov",
        type: "address",
      },
    ],
    name: "initGov",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_newOwner",
        type: "uint256",
      },
    ],
    name: "proposeTransferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "enum OwnerDataTypes.Action",
        name: "_action",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "proposeUpdatePauser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CommonOwnerProxy__factory {
  static readonly abi = _abi;
  static createInterface(): CommonOwnerProxyInterface {
    return new utils.Interface(_abi) as CommonOwnerProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CommonOwnerProxy {
    return new Contract(address, _abi, signerOrProvider) as CommonOwnerProxy;
  }
}
