/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OwnerProxyBase,
  OwnerProxyBaseInterface,
} from "../OwnerProxyBase";

const _abi = [
  {
    inputs: [],
    name: "gov",
    outputs: [
      {
        internalType: "contract SimpleGovernance",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract SimpleGovernance",
        name: "_gov",
        type: "address",
      },
    ],
    name: "initGov",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class OwnerProxyBase__factory {
  static readonly abi = _abi;
  static createInterface(): OwnerProxyBaseInterface {
    return new utils.Interface(_abi) as OwnerProxyBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnerProxyBase {
    return new Contract(address, _abi, signerOrProvider) as OwnerProxyBase;
  }
}
